title: Beverbende
baseurl: "/LAMAS" # the subpath of your site, e.g. /blog
url: "https://sanneberends.github.io" # the base hostname & protocol for your site, e.g. http://example.com

header_pages:
  - index.md
  - original_game.md
  - simplifications.md
  - implementation.md
  - formal_modal.md
  - example.md
